### ISSUE TITLE
ukol1

### ISSUE THREAD

**Issue by ZuzaGold** [ZuzaGold/Programovani_v_Pythonu#3]
zasekla jsem se na začátku

**Comment by srpwnd** [comment]
Sepíšu ti tady pár poznámek a nápověd 😊 

V zásadě na to jdeš dobře, ale máš tam pár překlepů a nesrovnalostí. Vezmu to od vrchu dolu:

---

```python
pizza = {                   # Název, cena
    "Margarita", 200,
    "Prosciuto", 180,
    "Salami", 190
}
```

S touto množinou nikde dál nepracuješ, ale předpokládám, že jsi tím chtěla definovat druhy pizzy a jejich ceny. V našem případě bychom s tím chtěli pracovat spíše takto:

```python
margarita = Pizza("margarita", 180, {"sýr": 100, "rajčata": 150})
prosciuto = Pizza("prosciuto", 195, {"sýr": 100, "rajčata": 150, "sunka": 200})
...
```

---

```python
drink = {                   # Název nápoje, množství v ml
    "cola": 500,
    "soda": 500,
    "sprite": 500,
    "mirinda": 500
}
```

Tady podobně jako u pizzy

```python
cola = Drink("cola", 45, 500)
...
```

---

```python
    def __str__(self):
        return f"Zákazník {self.custormer_name} s adresou {self.delivery_address} objednal: {self.items}, objednávka {self.status}."
```

Tady máš překlep v názvu proměnné `self.custoRmer_name` -> `self.customer_name`.

---

```python
# order_1 = Order("Jaroslav Novák", "Palackého 233, Klatovy", "Margarita", "sýr", "soda")
# order_2 = Order("paní Krásná", "Záletná 20, Lhotka", "Prosciuto", "olivy", "cola")
# order_3 = Order("pan Nerd", "V Koncích 1, Hůrka", "Salami", "mirinda")

order = (
    ["Jaroslav Novák", "Palackého 233, Klatovy", "Margarita", "sýr", "soda"],
    ["paní Krásná", "Záletná 20, Lhotka", "Prosciuto", "olivy", "cola"],
    ["pan Nerd", "V Koncích 1, Hůrka", "Salami", "mirinda"]
)
```

Tady máš v zásadě správně to, co máš zakomentované jako definici objednávek, ale jako parametr `item` očekáváme seznam objektů, např.:

```python
margarita = Pizza("margarita", 180, {"sýr": 100, "rajčata": 150})
cola = Drink("cola", 45, 500)

order = Order("Jaroslav Novák", "Palackého 233, Klatovy", [margarita, cola])
```

---

```python
    def assign_order(self, order):
        if self.available:
            self.current_order = order
            # self.current_order.status = "Na cestě"
            return f"Objednávka {self.current_order} byla přiřazena doručovateli {self.name_person} s telefonem {self.phone_number}."
        else:
            self.available = False
            return f"Bohužel momentálně není doručovatel k dispozici."
```

Toto máš správně a dokonce i ten kus zakomentovaného kódu k nastavení stavu objednávky, takže ho můžeš odkomentovat.

---

```python
    def complete_delivery(self):
        if self.current_order:
            self.current_order.mark_delivered()
            return f"Objednávka byla přiřazena doručovateli {self.name_person}, telefonní číslo {self.phone_number}."
            # self.current_order = None
            # self.available = True
```

Tady také ten zakomentovaný kód je správně, pouze o musíš přesunout nad klíčové slovo `return`, protože v momentě kdy se tento return vykoná, tak se funkce ukončí a nic dalšího už se v ní nestane.

---

```python
deliveryPerson = (                  # Jméno doručovatele, telefon
    ["Orlando", 775432234],
    ["George", 774123345],
    ["Brandon", 775123321]
)
```

Podobně jako v předchozích případech chceme doručovatele definovat jako instance třídy `DeliveryPerson`, tak jak máš na konci souboru.

---

```python
deliveryPerson.assing_order(order[0])
```

tady máš překlep v názvu funkce `assing` -> `assign`

---

Doufám, že jsem to dobře popsal. Kdyby bylo něco nejasného, tak se kdykoliv ozvi.

**Comment by ZuzaGold** [comment]
Dneska jsem se pro změnu zasekla u sečítání ceny objednávky. Nejdřív jsem to chtěla počítat ještě před třídou Order, ale tam mi to nešlo, tak jsem zkusila v rámci třídy Order jiným způsobem, ale nedaří se mi udělat správně kód a tím pádem ani volání funkce. 
Ale vypsání objednávky, přiřazení doručovatele a doručení objednávky se mi podařilo. Takže alespoň část už mám hotovou. Snad dobře.... Jo, ještě jsem si vzpomněla, že když jsem zvolila jako přidanou ingredienci takovou, která je i součástí pizzy, tak místo, aby se to množství přičetlo, tak se původní složka pizzy nahradí jen tou přidanou - to mě přišlo zvláštní (například můžeš přidat sýr)...

**Comment by ZuzaGold** [comment]
dneska jsem ještě pokračovala, ale zatím jsem sem nevkládala další verzi. 
ze včerejšího  kódu jsem zjistilla, že mi tam kvůli počítání ceně nefunguje ani to, co už mi fungovalo. Celý jsem si to rozhodila... tak dneska jsem něco dala do pořádku, ale včera před úpravami mi to aspoň vykazovala přiřazení objednávky doručovateli, vypsalo mi to doručovatele a jeho jméno a že byla objednávka doručena. Spočetla se mi cena za pizzu s přidanou ingrediencí.
Ale ať dělám co dělám, dnes se mi nepočítá žádná cena. Vůbec se mi nepropisuje, ani základní cena pizzy, ani za ingredienci ani za drink. Natož aby se sečetla dohromady... Mám tedy vložit i tuto nepovedenou verzi?

**Comment by ZuzaGold** [comment]
nová verze vložena

**Comment by srpwnd** [comment]
Ahoj Zuzko, počítat celkovou cenu objednávky není v zadání, takže to nemusíš řešit (ale ukážu ti jak na to na konci zprávy) 😊 

Už jen pár drobností na doladění:

---

```python
    def add_extra(self, ingredient, quantity, price_per_ingredient):
        if ingredient in self.ingredient_prices:
            self.ingredient = ingredient
            self.quantity = quantity
            self.price_per_ingredient = price_per_ingredient
            self.ingredients[ingredient] = quantity
            self.price += quantity * price_per_ingredient        
        else:
            print(f"Ingredience navíc {self.ingredient_prices} není k dispozici")
```

Nejvíc bojuješ s touto metodou třídy `Pizza`, takže jí společně trochu upravíme.

V první podmínce zkoušíš, zda ingredience již je mezi ingrediencemi, což je velmi dobrá úvaha, ale bohužel špatně technicky provedená. Je to tak, jelikož kontroluješ, zda je ingredience v proměnné `self.ingredient_prices`, a nikoliv `self.ingredients`.

```python
        if ingredient in self.ingredient_prices:
                              ^^^^^^^^^^^^^^^^^
        # spis chceme toto:
        if ingredient in self.ingredients:
```

Je to z toho důvodu, že v objektu Pizza není nikde proměnná `ingredient_prices` definovaná a tím pádem nemáme vůči čemu porovnávat.

Teď, když máme správně přiřazený název proměnné, tak je potřeba podmínku ještě "otočit", protože chceme ingredienci přidávat v případě, kdy _není_ již mezi ingrediencema na pizze:

```python
        if ingredient in self.ingredients:
                      ^^
        # pridanim `not` kontrolujeme zda tam neni:
        if ingredient not in self.ingredients:
```

Pak už můžeme radostně přidávat novou ingredienci 💪 

Když se ještě podíváme dále, tak přiřazuješ informace o jednotlivé ingredienci do vlastních proměnných v dané třídě, což ale nepotřebujeme:

```python
            # vsechno toto muzeme vymazat
            self.ingredient = ingredient
            self.quantity = quantity
            self.price_per_ingredient = price_per_ingredient
```

Protože veškeré informace si chceme držet ve slovníku `ingredients` a proměnné `price`, tak jak máš tady:

```python
            # toto je spravne a staci pro pridani ingredience a vypocet ceny
            self.ingredients[ingredient] = quantity
            self.price += quantity * price_per_ingredient 
```

Nakonec je ještě potřeba upravit druhou část podmínky, kde opět přistupuješ k neexistující proměnné `ingredient_prices`:

```python
        else:
            print(f"Ingredience navíc {self.ingredient_prices} není k dispozici")
                                            ^^^^^^^^^^^^^^^^^
```

---

```python
    # def __str__(self):
    #     ingredients_str = ", ".join([f"{ingredient} ({quantity} g)" for ingredient, quantity in self.ingredients.items()]) 
    #     return f"Pizza {self.name} - Ingredience: {ingredients_str}, stojí celkem {self.price} Kč."

    def __str__(self):
        return f"Pizza {self.name} s ingrediencí {self.ingredient} stojí celkem {self.price} Kč."
```

Na základě úprav výše pak zase bude fungovat ta zakomentovaná varianta výpisu, což je i ta vhodnější 😊 

---

```python
    def __str__(self):
        item_list = "/".join([str(item) for item in self.items])
        return f"{self.status}: {self.customer_name} / {self.delivery_address} / {self.items}."
```

V této části výpisu si krásně nachystáš proměnnou `item_list`, která obsahuje čitelný výpis položek objednávky ve stringu, a pak ji nepoužiješ a necháš vypisovat přímo `self.items`, což vypíše jen škaredou interní reprezentaci objektu. Zkus to nahradit 😊 

---

```python
    def __str__(self):
            availability = "available" if self.available else "not available"
            return f"Doručovatel {self.name_person} nemá žádnou objednávku k doručení."
```

Tady obdobně jako v předchozím bodě si nachystáš informaci o dostupnosti kurýra, ale pak ji nepoužiješ a ve všech případech vypisuješ, že kurýr nemá žádnou objednávku.

---

Tady ještě upozornění k tomu, co definuješ na konci souboru:

```python
Order = pani_Krasna
```

Tímto výše přepíšeš definici třídy `Order` na hodnotu proměnné `pani_Krasna`. Dej si pozor na to, abys takto nepřepisovala takto existující definice, protože ti to pak v půlce kódu přestane fungovat. Je dobrá konvence nepojmenovávat proměnné s velkým písmenem. Totéž platí i pro následující řádek:

```python
DeliveryPerson = Orlando
```

Poté se totiž zbytečně mateš tím, jak používat funkce tříd, protože v tento moment už `DeliveryPerson` není definice třídy, ale instance a proto ti to funguje:

```python
print(DeliveryPerson.assign_order(pani_Krasna))
```

Ale zároveň ti to tady takto nefunguje s pizzou:

```python
print(Pizza.price)
```

Protože `Pizza` je stále jen definice třídy a u definic třídy nemůžeme přistupovat k jejím funkcím a proměnným, to lze jen u instancí daných tříd.

Když upravíš ty výše popsané problémy, můžeš tento konec souboru s výpisy nahradit tím kontrolním kusem kódu z konce zadání a bude to fungovat správně 😊 💪 

---

_Zde slíbený způsob, jak vypočítat cenu objednávky. Do definice třídy `Order` si můžeš přidat další metodu, která sečte ceny jednotlivých položek v seznamu `items`:_

```python
    def total_price(self):
        sum = 0
        for item in self.items:
            sum += item.price
        return sum
```

**Comment by ZuzaGold** [comment]
Ahoj Pavle, můžeš kouknout, jestli už je úkol splněn? 
Snažila jsem se odstranit ty chyby a upravit kód tak, aby to fungovalo. Pro kontrolu jsem zadala objednávku pana Nováka, která není doručená, abych mohla vyzkoušet, že doručovatel není k dispozici pro objednávku paní Krásné. A pak objednávka pana Nerda zase zkouší, jestli už je volný Orlando, který doručoval objednávku paní Nové. Za mě to asi funguje...
... děkuji za sčítací metodu, tu si budu zkoušet, až budu mít splněný úkol

**Comment by srpwnd** [comment]
Ahoj Zuzko, skvělá práce, děkuju! Úkol máš tímto splněn 😊
