### ISSUE TITLE
úkol Obchodní rejstřík

### ISSUE THREAD

**Issue by ZuzaGold** [ZuzaGold/Programovani_v_Pythonu#4]
Ahoj Pavle, 
udělala jsem zatím úkol se zadanými příklady IČ a název moneta, abych viděla, jestli mi to dává "dobrý" výsledek... V podstatě mi to vyjelo správně, ale vždycky se mi tam přidají i všechna data subjektů, takže ten výsledek se ztrácí v nedohlednu....

**Comment by srpwnd** [comment]
Ahoj Zuzko,

nemám tomu co vytknout. Je to moc pěkne zpracované a kód je hezky strukturovaný a dobře čitelný. Zobrazuje to přesně takové výsledky, které má.

Děkuji za vypracování a označuji úkol za splněný 💪
